# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: chillyBlue
email: william@chilly.blue
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chilly.blue" # the base hostname & protocol for your site
github_username:  williamchiu
description: The personal website of Billy Chiu.

permalink: pretty

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
    style: compressed
