# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: chilly.blue
email: william@chilly.blue
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chilly.blue" # the base hostname & protocol for your site
github_username:  williamchiu
twitter_username: aChillyBlue
description: A personal blog of Billy Chiu.
license: This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>

permalink: pretty

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5

paginate_path: "/posts/page:num/"

excerpt_separator: ""

compress_html:
  blanklines: true
  clippings: all

sass:
    style: compressed

social_media:
  - icon: facebook-box
    url: https://www.facebook.com/billychillybluechiu
  - icon: github-box
    url: https://github.com/WilliamChiu
  - icon: linkedin-box
    url: https://www.linkedin.com/in/william-chiu
  - icon: email
    url: mailto:william@chilly.blue
  - icon: file-document
    url: /media/wnc2105Resume.pdf

defaults:
  - scope:
      path: ""
    values:
      image: /favicons/mstile-310x310.png

